library(e1071)

outFile <- "Validation/R_Validation.ecl"
outText <- ""

heart_scale <- read.csv("Datasets/heart_scale.csv", header = F)

x <- heart_scale[,-1]
y = heart_scale[,1]

getECL <- function(x, y, scale, regress) {
  svmMdl <- svm(
    x           = if (scale) scale(x) else x,
    y           = if (regress) y else as.factor(y),
    type        = if (regress) "eps-regression" else "C-classification",
    kernel      = "radial",
    gamma       = 0.1,
    probability = T,
    scale       = F,
    fitted      = T
  )
  probs <- attr(predict(svmMdl, if (scale) scale(x) else x, probability = TRUE), "probabilities")[,c(2,1)]
  preds <- if (regress) svmMdl$fitted else 2*(as.integer(probs[,1] <= probs[,2])-0.5)

  rslt <- c("// scale = ", if (scale) "T" else "F", "\n\n")

  suffix <- paste0(if (regress) "_SVR_" else "_SVC_", if (scale) "Scaling" else "NoScaling")
  test <- paste0(if (regress) "'SVR, " else "'SVC,", if (scale) "with scaling'" else "without scaling'")

  rslt <- c(rslt, paste0("EXPORT NumberOfSVs",suffix),":=", svmMdl$tot.nSV, ";\n")
  rslt <- c(rslt, paste0("EXPORT SVCoefs",suffix),":= DATASET([\n")
  rslt <- c(rslt, "{", paste0(paste0(1:svmMdl$tot.nSV, ", ", test, ", ", svmMdl$coefs), collapse = "}, {"), "}\n")
  rslt <- c(rslt, "], {INTEGER ID, STRING20 Test, REAL8 R});\n")
  rslt <- c(rslt, paste0("EXPORT Predictions",suffix),":= DATASET([\n")
  rslt <- c(rslt, "{", paste0(paste0(1:nrow(x), ", ", test, ", ", preds), collapse = "}, {"), "}\n")
  rslt <- c(rslt, "], {INTEGER ID, STRING20 Test, REAL8 R});\n")
  if (!regress) {
    rslt <- c(rslt, paste0("EXPORT Probabilities",suffix), ":= DATASET([\n")
    rslt <- c(rslt, "{", paste0(paste0(1:nrow(x), ", ", test, ", ", probs[,2]), collapse = "}, {"), "}\n")
    rslt <- c(rslt, "], {INTEGER ID, STRING20 Test, REAL8 R});\n\n")
  } else {
    rslt <- c(rslt, "\n\n")
  }
}

outText <- c(outText, "//////// CODE AUTO-GENERATED BY R\n")
outText <- c(outText, "EXPORT R_Validation := MODULE\n\n")
outText <- c(outText, "//// Get coefficients and predictions for SVC\n\n")
outText <- c(outText, getECL(x, y, F, F))
outText <- c(outText, getECL(x, y, T, F))

outText <- c(outText, "//// Get coefficients and predictions for SVR\n\n")
outText <- c(outText, getECL(x, y, F, T))
outText <- c(outText, getECL(x, y, T, T))

outText <- c(outText, "//// Run SVC grid search and get accuracies\n\n")

tuneResults <- tune(
  ranges      = list(
    gamma       = 2^seq(-15, 3, length.out = 10),
    cost        = 2^seq(-5, 15, length.out = 12)),
  tunecontrol = tune.control(
    nrepeat     = 1,
    sampling    = "cross",
    cross       = 10,
    best.model  = F),
  method      = svm,
  train.x     = scale(x),
  train.y     = as.factor(y),
  type        = "C-classification",
  kernel      = "radial",
  probability = F,
  scale = F
)
tuneAccuracy <- tuneResults$performances
outText <- c(outText, "EXPORT GridSearchResults_SVC := DATASET([\n")
outText <- c(outText, paste0("{", paste(1:nrow(tuneAccuracy), tuneAccuracy$cost, tuneAccuracy$gamma, paste0(tuneAccuracy$error, "}"), sep = ", "), collapse = ",\n "))
outText <- c(outText, "\n], {INTEGER ID, REAL8 Cost, REAL8 Gamma, REAL8 R});\n\n")

outText <- c(outText, "//// Run SVR grid search and get accuracies\n\n")

tuneResults <- tune(
  ranges      = list(
    gamma       = 2^seq(-15, 3, length.out = 10),
    cost        = 2^seq(-5, 15, length.out = 12)),
  tunecontrol = tune.control(
    nrepeat     = 1,
    sampling    = "cross",
    cross       = 10,
    best.model  = F),
  method      = svm,
  train.x     = scale(x),
  train.y     = y,
  type        = "eps-regression",
  kernel      = "radial",
  probability = F,
  scale = F
)
tuneAccuracy <- tuneResults$performances
outText <- c(outText, "EXPORT GridSearchResults_SVR := DATASET([\n")
outText <- c(outText, paste0("{", paste(1:nrow(tuneAccuracy), tuneAccuracy$cost, tuneAccuracy$gamma, paste0(tuneAccuracy$error, "}"), sep = ", "), collapse = ",\n "))
outText <- c(outText, "\n], {INTEGER ID, REAL8 Cost, REAL8 Gamma, REAL8 R});\n\n")

outText <- c(outText, "END;")

cat(outText, file = outFile)
